# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required


r_packages:
  - testthat
  - covr

r_github_packages:
   - cancercentrum/rccmisc

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - Rscript -e 'covr::codecov()'
  
notifications:
  email:
    recipients:
      - erik.bulow@rccvast.se
    on_success: change
    on_failure: change
